### ISSUE TITLE
Setup husky + Prettier / cargo fmt for the monorepo

### ISSUE THREAD

**Issue by stuartlynn** [Matico-Platform/matico#211]
What I have used in the past which has worked pretty well is 

- [husky](https://typicode.github.io/husky/#/) to manage the pre-commit hooks.
- [Prettier](https://prettier.io/) to format typescript.
- cargo fmt to format rust code. Though it looks like there is a [community plugin](https://github.com/jinxdash/prettier-plugin-rust) for Prettier to allow it to work with rust as well, so perhaps we use that for both

While we are thinking about dev tooling as well, it might be worth considering using something akin to [comittizen](https://github.com/commitizen/cz-cli) to standardize commit messages and make it easier to produce release notes in future.

**Comment by michplunkett** [comment]
I think we could take this in a couple of steps, but I think comittizen is something we could eventually get in. I'll address this more some time on Friday afternoon.

**Comment by michplunkett** [comment]
I'll try to approach this in a couple of distinct PRs so that all changes are isolated:
1. Install Prettier in the code base
2. Run Prettier on TypeScript
3. Run Prettier on Rust
4. Install Husky
5. Configure Husky for the pre-commit hooks

This pathway obviously relies on Prettier being able to run on Rust, which it should, but should that not be the case I'll add 2 PRs for installing the Rust Prettier equivalent and then running it on the Rust code base.

**Comment by stuartlynn** [comment]
Sounds good to me. If prettier can't do rust well enough we should be able to just use "cargo fmt" which comes as standard with cargo the rust package manager.

Just a quick note to say because we have this setup as a monorepo, you prob want to install all of this at the root level, ie in the package.json in the root directory.

**Comment by michplunkett** [comment]
Yup, the root level is where I'm installing it! Given that I went with Google's TypeScript formatter, I think I'll be using `cargo fmt`.

**Comment by michplunkett** [comment]
With the merging of https://github.com/Matico-Platform/matico/pull/222, this PR is done.
